### PR TITLE
Enhance/add debounce

### PR DESCRIPTION
**Pull request by kelanialiyu**
introduce debounce to reduce the number of request to firebase
and move firebase config files to env
fixes: #20 #21

### CODE REVIEW

**Comment by Indrajeet-S** [comment]
Thank you! 😄

**Comment by Indrajeet-S** [comment]
Thanks 💯

**Comment by kelanialiyu** [comment]
can you add the hacktoberfect badges to them

**Comment by Indrajeet-S** [comment]
> can you add the hacktoberfect badges to them
> 

Ok

**Comment by kelanialiyu** [comment]
I am still open to contribute is there a communication channel

**Comment by Indrajeet-S** [comment]
Cool, rn there is no communication channel but I can create a discord server or you can DM me on discord (`qbit_069`). Also always open to raise issues and PRs no problem. Alright, thank you again for your valuable contributions!

**Comment by Indrajeet-S** [comment]
> Cool, rn there is no communication channel but I can create a discord server or you can DM me on discord (`qbit_069`). Also always open to raise issues and PRs no problem. Alright, thank you again for your valuable contributions!

@kelanialiyu

**Pull request merged**
