### PR TITLE
Fix/firebase persistence error fixes: #1

### LINKED ISSUE #1: Fix: Data is not getting stored in Firestore
For example, after doing a refresh or while accessing that problem ID again the page doesn't have persistence and data is not getting stored in the Firestore database. Find what is the exact issue is. 
Before: 
image
After: 
image

Definition of done: 
- Data should be persistent and it should be stored in the Firestore database (for reference: I made the commit regarding persistence to local storage you can see)

### PR DESCRIPTION
**Pull request by kelanialiyu**
moved all firebase read and wirte action to the server

### CODE REVIEW

**Comment by kelanialiyu** [comment]
Hi I have a pr can you take a look

**Comment by kelanialiyu** [comment]
fixes: #1

**Comment by Indrajeet-S** [comment]
See the deployment preview [link](https://leetcode-board-he7ibvtpa-indrajeet-s-projects.vercel.app/problems/2)
What's wrong? 
image 
Server side log for `/problems/problemID` is: 
```
[2024-10-31T16:32:47.439Z]  @firebase/firestore: Firestore (10.14.1_lite): RestConnection RPC 'BatchGetDocuments' 0x31ada75e failed with error:  [E [FirebaseError]: Request failed with error: Missing or insufficient permissions.] {
  code: 'permission-denied',
  customData: undefined,
  toString: [Function (anonymous)]
} url:  https://firestore.googleapis.com/v1/projects/leetcode-board-373e7/databases/(default)/documents:batchGet request: {
  documents: [
    'projects/leetcode-board-373e7/databases/(default)/documents/excalidraw/234'
  ]
}
```
```
[E [FirebaseError]: Request failed with error: Missing or insufficient permissions.] {
  code: 'permission-denied',
  customData: undefined,
  toString: [Function (anonymous)],
  digest: '3446604106'
}
```

Environment variables are set tho: 
image

@kelanialiyu

**Comment by kelanialiyu** [comment]
Hello QBit, yes, I had a similar problem when setting up my firebase project.
check the firebase project leetcode-board-373e7, ensure it has rules are sufficient for the app to write from the server
here is an example of one I created.
image

**Comment by kelanialiyu** [comment]
albeit this rule is very lax, you can also experiment with service accounts, or IAM for a more robust and secured approach

**Comment by Indrajeet-S** [comment]
> check the firebase project leetcode-board-373e7, ensure it has rules are sufficient for the app to write from the server
> here is an example of one I created.

Okay, let me do this!!

**Comment by Indrajeet-S** [comment]
Still same thing 
```
Application error: a server-side exception has occurred (see the server logs for more information).

Digest: 3446604106
```
image

I even redeployed and checked it!

**Comment by Indrajeet-S** [comment]
or this will work after a merge? 🫠

**Comment by kelanialiyu** [comment]
Hi this rule allows only authenticated user to store data.

**Comment by Indrajeet-S** [comment]
> Hi this rule allows only authenticated users to store data.

Cool! I did this for now: `allow read, write: if true;` until authentication `signin` and `signup` are not set up completely. After that, we can have a persistence feature for authenticated users only.

**Comment by Indrajeet-S** [comment]
Thank you so much for your contribution!!!

**Pull request merged**
